[project]
name = "coinquest"
description = "A gamified DeFi savings and quest platform built on Stacks blockchain for the Vibe Coding Hackathon"
authors = ["coinQuest Team"]
license = "MIT"

[contracts.CoinQuestToken]
path = "contracts/CoinQuestToken.clar"
depends_on = []

[contracts.CoinQuestGame]
path = "contracts/CoinQuestGame.clar"
depends_on = ["CoinQuestToken"]

[requirements]
clarinet = ">=3.0.0"
