/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { ISkyRunToken__factory } from "./ISkyRunToken__factory";
export { SkyRunGame__factory } from "./SkyRunGame__factory";
