/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  ISkyRunToken,
  ISkyRunTokenInterface,
} from "../../../contracts/SkyRunGame.sol/ISkyRunToken";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "to",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "mint",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class ISkyRunToken__factory {
  static readonly abi = _abi;
  static createInterface(): ISkyRunTokenInterface {
    return new Interface(_abi) as ISkyRunTokenInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): ISkyRunToken {
    return new Contract(address, _abi, runner) as unknown as ISkyRunToken;
  }
}
