/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as skyRunGameSol from "./SkyRunGame.sol";
export * as hts from "./hts";
export { SkyRunToken__factory } from "./SkyRunToken__factory";
