/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IHederaTokenService,
  IHederaTokenServiceInterface,
} from "../../../contracts/hts/IHederaTokenService";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "token",
        type: "address",
      },
      {
        internalType: "int64",
        name: "amount",
        type: "int64",
      },
      {
        internalType: "bytes[]",
        name: "metadata",
        type: "bytes[]",
      },
    ],
    name: "mintToken",
    outputs: [
      {
        internalType: "int32",
        name: "responseCode",
        type: "int32",
      },
      {
        internalType: "int64",
        name: "newTotalSupply",
        type: "int64",
      },
      {
        internalType: "int64[]",
        name: "serialNumbers",
        type: "int64[]",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "token",
        type: "address",
      },
      {
        internalType: "address[]",
        name: "accountIds",
        type: "address[]",
      },
      {
        internalType: "int64[]",
        name: "amounts",
        type: "int64[]",
      },
    ],
    name: "transferTokens",
    outputs: [
      {
        internalType: "int32",
        name: "responseCode",
        type: "int32",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IHederaTokenService__factory {
  static readonly abi = _abi;
  static createInterface(): IHederaTokenServiceInterface {
    return new Interface(_abi) as IHederaTokenServiceInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IHederaTokenService {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as IHederaTokenService;
  }
}
