/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as skyRunGameSol from "./SkyRunGame.sol";
export type { skyRunGameSol };
import type * as hts from "./hts";
export type { hts };
export type { SkyRunToken } from "./SkyRunToken";
